"""SOFTWARE UNIT TESTS. Generated bytes and images are not scientific evidence."""
from __future__ import annotations

import hashlib
from pathlib import Path
import sys
import tempfile
import unittest
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from astra_piv.config import ProvenanceConfig
from astra_piv.provenance import inspect_video_provenance, source_evidence_flags


class TestSourceIdentity(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.cfg = ProvenanceConfig()
        self.video = Path(self.temp.name) / self.cfg.canonical_video_basename
        self.video.write_bytes(b"synthetic test fixture, not video evidence")
        self.probe = {"streams": [{"avg_frame_rate": str(self.cfg.legacy_sampling_hz), "nb_frames": "5000"}]}

    def inspect(self):
        with patch("astra_piv.provenance.ffprobe_video", return_value=self.probe):
            return inspect_video_provenance(self.video, self.cfg)

    def trust_fixture(self):
        self.cfg.canonical_sha256 = hashlib.sha256(self.video.read_bytes()).hexdigest()
        self.cfg.canonical_reference = "SOFTWARE TEST fixture definition"

    def test_name_and_fps_never_prove_identity(self):
        self.assertFalse(self.inspect().publication_ready_source)

    def test_digest_without_reference_is_blocked(self):
        self.trust_fixture()
        self.cfg.canonical_reference = None
        self.assertFalse(self.inspect().publication_ready_source)

    def test_wrong_digest_is_blocked(self):
        self.trust_fixture()
        self.cfg.canonical_sha256 = "0" * 64
        self.assertFalse(self.inspect().publication_ready_source)

    def test_wrong_byte_size_is_blocked(self):
        self.trust_fixture()
        self.cfg.canonical_size_bytes = 1
        self.assertFalse(self.inspect().publication_ready_source)

    def test_malformed_digest_is_rejected(self):
        self.cfg.canonical_sha256 = "not-a-digest"
        with self.assertRaises(ValueError):
            self.inspect()

    def test_unavailable_frame_count_is_not_invented(self):
        self.probe["streams"][0]["nb_frames"] = "N/A"
        self.assertIsNone(self.inspect().frame_count)

    def test_source_identity_is_separate_from_acquisition_timing(self):
        self.trust_fixture()
        self.probe["streams"][0]["avg_frame_rate"] = "30/1"
        prov = self.inspect()
        self.assertTrue(prov.publication_ready_source)
        self.assertFalse(prov.acquisition_timing_resolved)
        flags = source_evidence_flags(prov, {}, {})
        self.assertFalse(flags["delta_t_resolved"])
        self.assertFalse(flags["full_raw_video_scanned"])

    def test_timing_requires_positive_value_and_evidence(self):
        self.cfg.acquisition_dt_s = self.cfg.legacy_dt_s
        self.assertFalse(self.inspect().acquisition_timing_resolved)
        self.cfg.acquisition_dt_reference = "SOFTWARE TEST clock certificate"
        self.assertTrue(self.inspect().acquisition_timing_resolved)
        self.cfg.acquisition_dt_s = float("nan")
        self.assertFalse(self.inspect().acquisition_timing_resolved)


if __name__ == "__main__":
    unittest.main()
